language: python
sudo: false

matrix:
  include:
    # Linting
    - python: 2.7
      env: TOXENV=lint

    - python: 3.6
      env: TOXENV=lint

    # Packaging
    - python: 3.6
      env: TOXENV=packaging

    # Linux Builds
    - python: 2.7
      env: TOXENV=py27
      
    - python: 3.4
      env: TOXENV=py34

    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36

    - python: nightly
      env: TOXENV=py37
      
    # Mac OS Builds
    - os: osx
      language: generic
      env: TOXENV=py27
      
    - os: osx
      language: generic
      env: TOXENV=py34

    - os: osx
      language: generic
      env: TOXENV=py35

    - os: osx
      language: generic
      env: TOXENV=py36

    - os: osx
      language: generic
      env: TOXENV=py37

  allow_failure:
    - python: nightly

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - chmod a+x .travis/install.sh .travis/script.sh
  - ./.travis/install.sh 

script:
  - ./.travis/script.sh

after_success:
  - source .tox/${TOXENV}/bin/activate
  - python -m pip install codecov
  - codecov --env TRAVIS_OS_NAME,TOXENV

notifications:
  email: false

branches:
  only:
  - master
